# Generated by Django 5.2.4 on 2025-08-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(default='Cairo', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_usage', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('-last_usage',),
            },
        ),
    ]
